a = input('Digite algo :')
print('O tpo primitivo desse valor é', type(a))
print('Só tem espaço?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanúmericco?', a.isalnum())
print('Esta em maiúscula?', a.isupper())
print('Esta em minúsculas', a.islower())
print('Esta capitalizada?', a.istitle())
